---
title: "Chess Over Time"
author: "Jay Shapiro"
date: "TBD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Reminder: Figure out how to parse data with several different delimiters

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(plotly)
library(plyr)
library(data.table)
library(readr)
library(dplyr)
library(ggfortify)

#Grab the file names of the ratings lists for each month
myfiles <- list.files(path = "C:/Users/OneCalledSyn/Desktop/FIDE/Historical_Ratings", 
                      pattern = "*.txt", full.names = TRUE)

FIDE_players <- data.frame()

for (lambda in c(1:length(myfiles))) {
  location <- myfiles[lambda]
  temp <- fread(file = location, 
                sep = "\t", fill = TRUE, header = TRUE)
  
  FIDE_players <- rbind(FIDE_players, temp)
  
}
# FIDE_players <- read.delim("C:/Users/OneCalledSyn/Desktop/FIDE/july_2000.txt", 
#                           header = TRUE, sep = "\t")
str(FIDE_players)
dim(FIDE_players)
head(FIDE_players)

p <- ggplot(FIDE_players[1:105, ], aes(x = `B-Year`, y = Rating, color = Games)) + geom_point()

ggplotly(p)

rank_1_FIDE_players <- FIDE_players[Rank == 1]

```

<br><br>